version: "3.8"
services:
  api:
    image: pytree:0.0.1
    environment:
      DEPLOY_ENV: ${DEPLOY_ENV:-DEV}
    restart: unless-stopped
    build: .
    volumes:
      - "${DATA_DIR:-processed}:/home/pytree/data/processed"
    ports:
      - "${PORT:-5000}:5000"

volumes:
  processed:
