version: "3.8"

services:
  api:
    image: sitn/pytree:1.0
    environment:
      DEPLOY_ENV: ${DEPLOY_ENV:-DEV}
    restart: unless-stopped
    command: /app/start_server.sh
    volumes:
      - "${DATA_DIR}:/app/data"
    ports:
      - "${PORT:-6001}:5000"
